# Generated by Django 5.0 on 2024-01-30 10:14

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting payment", "Awaiting Payment"),
                            ("payment received", "Payment Received"),
                            ("shipped", "Shipped"),
                            ("completed", "Completed"),
                            ("refunded", "Refunded"),
                            ("canceled", "Canceled"),
                            ("failed", "Failed"),
                        ],
                        default="awaiting payment",
                        max_length=63,
                    ),
                ),
                ("delivery_region", models.CharField(max_length=255)),
                ("delivery_city", models.CharField(max_length=255)),
                (
                    "delivery_nova_post_department",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("customer_first_name", models.CharField(max_length=255)),
                ("customer_last_name", models.CharField(max_length=255)),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "customer_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="UA"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
        ),
    ]
