# Generated by Django 5.0 on 2023-12-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting payment", "Awaiting Payment"),
                    ("payment received", "Payment Received"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("canceled", "Canceled"),
                    ("FILED", "Filed"),
                ],
                default="awaiting payment",
                max_length=63,
            ),
        ),
    ]
