# Generated by Django 5.0 on 2024-01-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_city",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_nova_post_department",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_region",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
