# Generated by Django 5.0 on 2024-02-05 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_region",
        ),
    ]
