# Generated by Django 5.0 on 2024-01-07 19:23

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_customer_email_order_customer_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="0996649569", max_length=128, region="UA"
            ),
            preserve_default=False,
        ),
    ]
