# Generated by Django 5.0 on 2024-01-30 10:14

import autoslug.fields
import django.core.validators
import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(default="Category description...")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("hex", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text="please mark related product", max_length=255
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("xs", "Xs"),
                            ("s", "S"),
                            ("m", "M"),
                            ("l", "L"),
                            ("xl", "Xl"),
                            ("xxl", "Xxl"),
                            ("xxxl", "Xxxl"),
                            ("oversize", "Oversize"),
                        ],
                        max_length=15,
                    ),
                ),
                ("length", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("width", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("fabric", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        null=True,
                        populate_from=products.models.compose_slug,
                        unique=True,
                    ),
                ),
                ("stock", models.PositiveSmallIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="products.color",
                    ),
                ),
                (
                    "related_items",
                    models.ManyToManyField(blank=True, to="products.item"),
                ),
                (
                    "size",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="products.size",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "item",
                    models.ManyToManyField(
                        blank=True, related_name="images", to="products.item"
                    ),
                ),
            ],
        ),
    ]
