# Generated by Django 5.0 on 2024-01-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="image",
            name="item",
        ),
        migrations.AddField(
            model_name="image",
            name="item",
            field=models.ManyToManyField(related_name="images", to="products.item"),
        ),
    ]
