# Generated by Django 5.0 on 2024-01-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_image_description_remove_image_item_image_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
