# Generated by Django 5.0 on 2024-01-01 12:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from=["model__name", "color__name", "size__value"],
                unique=True,
            ),
        ),
    ]
