# Generated by Django 5.0 on 2024-01-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="item",
            field=models.ManyToManyField(
                blank=True, related_name="images", to="products.item"
            ),
        ),
    ]
