# Generated by Django 5.0 on 2024-01-01 12:36

import autoslug.fields
import products.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_item_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from=products.models.compose_slug,
                unique=True,
            ),
        ),
    ]
