# Generated by Django 5.0 on 2024-01-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_item_model_item_category_item_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="related_items",
            field=models.ManyToManyField(blank=True, to="products.item"),
        ),
    ]
