# Generated by Django 5.0 on 2024-01-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="wishlist",
            field=models.ManyToManyField(
                blank=True, related_name="wishlist", to="products.product"
            ),
        ),
    ]
