# Generated by Django 5.0 on 2024-02-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="region",
        ),
        migrations.AlterField(
            model_name="user",
            name="nova_post_department",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
