# Generated by Django 5.0 on 2024-01-06 12:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_city_user_nova_post_department_user_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="UA"
            ),
        ),
    ]
