# Generated by Django 5.0 on 2024-01-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_item_related_items"),
        ("user", "0006_alter_user_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="wishlist",
            field=models.ManyToManyField(
                blank=True, related_name="wishlisted_by", to="products.item"
            ),
        ),
    ]
