# Generated by Django 5.0 on 2024-01-26 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments",
            "0002_alter_payment_session_id_alter_payment_session_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="money_to_pay",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
